# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PLZpL38c0ZvBx9CaOdLoArg71aPx9QPJ
"""

from sklearn.datasets import make_classification
import numpy as np

X, y = make_classification(
    n_samples=200,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    n_clusters_per_class=2,
    random_state=10,
    hypercube=True,
    class_sep=1.0
)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.scatter(X[:,0], X[:,1], c=y, cmap='coolwarm', s=80, edgecolor='k')
plt.title("Modified Dataset (Overlapping Classes)")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

from sklearn.linear_model import LogisticRegression
lor = LogisticRegression(penalty=None,solver='sag', max_iter=5000)
lor.fit(X,y)

print(lor.coef_)
print(lor.intercept_)

m1 = -(lor.coef_[0][0]/lor.coef_[0][1])
b1 = -(lor.intercept_/lor.coef_[0][1])

x_input = np.linspace(-3,3,100)
y_input = m1*x_input + b1

def gd(X,y):

    X = np.insert(X,0,1,axis=1)
    weights = np.ones(X.shape[1])
    lr = 0.5

    for i in range(5000):
        y_hat = sigmoid(np.dot(X,weights))
        weights = weights + lr*(np.dot((y-y_hat),X)/X.shape[0])

    return weights[1:],weights[0]

def sigmoid(z):
    return 1/(1 + np.exp(-z))

coef_,intercept_ = gd(X,y)

m = -(coef_[0]/coef_[1])
b = -(intercept_/coef_[1])

x_input1 = np.linspace(-5, 5, 200)


m = -1.2
b = 0.5

y_input1 = m * x_input1 + b

plt.figure(figsize=(12,7))


plt.plot(x_input, y_input, color='red', linewidth=3, label='Boundary 1')


plt.plot(x_input1, y_input1, color='black', linewidth=3, linestyle='--', label='Boundary 2')


plt.scatter(X[:,0], X[:,1], c=y, cmap='coolwarm', s=80, edgecolor='k')





plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("Decision Boundaries Comparison")

np.insert(X,0,1,axis=1)

X1 = np.insert(X,0,1,axis=1)
np.ones(X1.shape[1])

